name: FiguraAvatars
version: '${version}'
main: top.mrxiaom.figura.bukkit.FiguraAvatars
api-version: 1.21
softdepend:
  - PlaceholderAPI
authors: [ MrXiaoM ]
commands:
  figuraavatars:
    description: 'The main command of FiguraAvatars'
    aliases: [ fa, avatars ]

permissions:
  figura.avatars.open:
    description: '允许玩家打开自己的外观选择界面'
    default: true
  figura.avatars.open.other:
    description: '允许为其他玩家打开外观选择界面'
    default: op
  figura.avatars.admin:
    description: '允许使用 refresh, reload 等管理命令'
    default: op
  figura.upload:
    description: '核心权限：决定后端是否允许该玩家上传模型'
    default: false